### ISSUE TITLE
form-urlencoded version 3.0.1 breaks older browsers as it returns untranspiled code

### ISSUE THREAD

**Issue by liamsorsby** [iambumblehead/form-urlencoded#20]
Has version 3.0.1 been removed or accidentally published? It still exists in NPM and seems to use the untranspiled version of form-urlencode which breaks in older browsers.
It seems to relate to https://github.com/iambumblehead/form-urlencoded/blob/master/package.json#L4

**Comment by iambumblehead** [comment]
@liamsorsby would you advise me?

https://github.com/iambumblehead/form-urlencoded/issues/19

The ['module' value][0] was changed to reference the main 'form-urlencoded' file in the root folder of this package. I believe only systems supporting es6 modules should use the 'module' file, other systems should use the ['main' file.][1]

[0]: https://github.com/nodejs/node-eps/blob/4217dca299d89c8c18ac44c878b5fe9581974ef3/002-es6-modules.md#51-determining-if-source-is-an-es-module
[1]: https://docs.npmjs.com/files/package.json#main

**Comment by liamsorsby** [comment]
@iambumblehead we recently had our react apps include this repo but unfortunately it included version 3.0.1 which caused I.e. 11 to break as it doesnt support arrow functions. Reverting back to 3.0.0 worked as expected though.

**Comment by liamsorsby** [comment]
Oh, we don't include this module directly. This was included as most versions are including this repo using ^3.0.0 which would include minor and patch versions. If this could break compatibility/behaviour this should be a major version  instead of a patch version.

**Comment by iambumblehead** [comment]
[The dist/form-urlencoded file does not have arrow functions.][0] To explicitly use the dist version of the file try using something like this is your application,
```javascript
import formurlencoded from 'form-urlencoded/dist/form-urlencoded';
```
@liamsorsby does this answer help? Politely, what build software are you using?

[0]: https://github.com/iambumblehead/form-urlencoded/blob/master/dist/form-urlencoded.js

**Comment by liamsorsby** [comment]
Unfortunately not, I provide some more details on Monday.

We use react and babel and this issue has occured twice now and caused issues with rendering our app on internet explorer. The fix was to force the dependency to use version 3.0.0 as it's not using the dist version in 3.0.1 due to the change noted above.

**Comment by iambumblehead** [comment]
@liamsorsby have you tried using [babel's][0] [babel-plugin-transform-arrow-functions?][1]

[0]: https://babeljs.io/docs/en/babel-plugin-transform-arrow-functions
[1]: https://www.npmjs.com/package/@babel/plugin-transform-arrow-functions

**Comment by liamsorsby** [comment]
@iambumblehead Yes, to clarify all our polyfills are based on our current browser support and it automatically polyfills and transpiles our code. I'll update this thread on Monday with some more indepth information.

**Comment by iambumblehead** [comment]
@liamsorsby I'll look forward to seeing your response. Humbly, I might suggest importing the non-dist version of the script if that is what you need instead,
```javascript
import formurlencoded from 'form-urlencoded/form-urlencoded';
```

**Comment by daveskybet** [comment]
@iambumblehead To add further details to @liamsorsby's comments, we use es6 imports and Webpack/Babel for the build (as is quite common), so as you say v3.0.1 is now using the 'module' file as the build system supports it, but Webpack doesn't transpile the node_modules directory so the untranspiled code ends up in the final bundle.

As you say, using `import formurlencoded from 'form-urlencoded/dist/form-urlencoded';` would fix this, however this is pretty non-standard and definitely shouldn't have been pushed as a patch version, and as @liamsorsby mentioned this module is being used by other modules we have as dependencies, rather than us importing directly, so these would have to be updated too. 

We could also amend our Webpack config to transpile node_modules, but this would slow down our build times so i don't really want to go down that route.

**Comment by iambumblehead** [comment]
@daveskybet and @liamsorsby my apology for responding late. Its almost 3pm here in California and I should have time to soon.

@daveskybet do you think adding a 'browser' property and value to the package.json pointing to the transpiled script would be sufficient? https://docs.npmjs.com/files/package.json#browser

Would you recommend a version number to which the changes should be published? Do you think '3.1.0' would be OK?

cc @frabarz if you happen to know anything about the way this should be published please comment

**Comment by daveskybet** [comment]
@iambumblehead I've not come across the browser field before, but it sounds like it's to be used instead of the main field, rather than as well as - `If your module is meant to be used client-side the browser field should be used instead of the main field.` - for specifying that the module will fail in a Node environment due to replying on things like `window`, rather than specifying transpiled/untranspiled versions.

The community seems to be a bit split on publishing ES2015+ code in modules (kind of a "you can if you want"), but one thing that's generally agreed on is clear documentation that consuming applications will need to specifically transpile this module (as Webpack ingores `node_modules`) due to ES2015 code or import from a different location (as your previous post suggested), and the release should be a new major version as a breaking change (so as to not break applications using `"form-urlencoded": "^3.0.0"`)

**Comment by frabarz** [comment]
according to [the spec](https://github.com/defunctzombie/package-browser-field-spec), the `browser` field [should solve this](https://github.com/webpack/webpack/issues/4674#issuecomment-355853969)
the whole list of params got messy quickly, [this guy compiled a list](https://github.com/stereobooster/package.json#package-bundlers) with more information on what each field should refer to

**Comment by iambumblehead** [comment]
@frabarz thank you for responding and sharing the helpful links.

@daveskybet and @liamsorsby please [review the changes here.][0] If the changes are OK, let's publish and see if the issues affecting you are resolved.

[0]: https://github.com/iambumblehead/form-urlencoded/pull/21/files

**Comment by iambumblehead** [comment]
Thanks everyone @frabarz @daveskybet and @liamsorsby.

Per your comments, a 3.0.2 version is published reverting the 'module' value to its previous state and a 4.0.0 version is published using the correct 'module' and 'browser' values from the pull request.

Feel free to reopen if needed

**Comment by liamsorsby** [comment]
Thanks @iambumblehead
